apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 1.10.0
    created: "2021-12-14T13:00:54.764765-08:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: 5c5c415745755c80f39b5fc5fc54a846d81ef72fdd27662e0fa6061e3d342f7e
    home: https://github.com/bitnami/charts/tree/master/bitnami/common
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: common
    sources:
    - https://github.com/bitnami/charts
    - https://www.bitnami.com/
    type: library
    urls:
    - charts/common-1.10.3.tgz
    version: 1.10.3
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.14.0
    created: "2021-12-14T13:00:54.77156-08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: e82781f3bc1895ba05c9873ce362e442485f5ad1c96eddaf24a9d7b10f0121b4
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.13.11.tgz
    version: 10.13.11
generated: "2021-12-14T13:00:54.763728-08:00"
