apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yatai.fullname" . }}
  labels:
    {{- include "yatai.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "yatai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "yatai.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "yatai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
          args:
            - exec /app/api-server serve -c /conf/config.yaml
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
          env:
            - name: PG_HOST
              value: {{ ternary (include "yatai.postgresql.host" .) .Values.externalPostgresql.host .Values.postgresql.enabled | quote }}
            - name: PG_DATABASE
              value: {{ ternary .Values.postgresql.postgresqlDatabase .Values.externalPostgresql.database .Values.postgresql.enabled }}
            - name: PG_PORT
              value: {{ ternary "5432" .Values.externalPostgresql.port .Values.postgresql.enabled | quote}}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "yatai.postgresql.secretName" . }}
                  key: {{ include "yatai.postgresql.existingsecret.key" . }}
            - name: PG_USER
              value: {{ ternary .Values.postgresql.postgresqlUsername .Values.externalPostgresql.user .Values.postgresql.enabled | quote }}
            - name: SESSION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "yatai.fullname" . }}
                  key: session_secret_key
            - name: YATAI_INITIALIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "yatai.fullname" . }}
                  key: initialization_token
            {{- if .Values.externalS3.enabled }}
            - name: S3_ENDPOINT
              value: {{ .Values.externalS3.endpoint }}
            - name: S3_REGION
              value: {{ .Values.externalS3.region }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.externalS3.bucketName }}
            - name: S3_SECURE
              value: {{ .Values.externalS3.secure }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalS3.existingSecret }}
                  key: {{ .Values.externalS3.existingSecretAccessKeyKey }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalS3.existingSecret }}
                  key: {{ .Values.externalS3.existingSecretSecretKeyKey }}
            {{- end }}
            {{- if .Values.externalDockerRegistry.enabled }}
            - name: DOCKER_REGISTRY_SERVER
              value: {{ .Values.externalDockerRegistry.server }}
            - name: DOCKER_REGISTRY_USERNAME
              value: {{ .Values.externalDockerRegistry.username }}
            - name: DOCKER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDockerRegistry.existingSecret }}
                  key: {{ .Values.externalDockerRegistry.existingSecretAccessKeyKey }}
            - name: DOCKER_REGISTRY_SECURE
              value: {{ .Values.externalDockerRegistry.secure }}
            - name: DOCKER_REGISTRY_BENTO_REPOSITORY_NAME
              value: {{ .Values.externalDockerRegistry.bentoRepositoryName }}
            - name: DOCKER_REGISTRY_MODEL_REPOSITORY_NAME
              value: {{ .Values.externalDockerRegistry.modelRepositoryName }}
            {{- end }}
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            httpGet:
              path: /
              port: http
          readinessProbe:
            failureThreshold: 60
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /conf
              name: config
              readOnly: true
            - mountPath: /etc/localtime
              name: host-timezone
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-timezone
        - name: config
          secret:
            secretName: {{ include "yatai.fullname" . }}
